---
- name: Reset Kubernetes component
  become: true
  ansible.builtin.shell:
    cmd: yes | kubeadm reset
  register: my_output
  changed_when: my_output.rc != 0

- name: Copy join command to worker nodes
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0700

- name: Join the Worker nodes with the master
  become: true
  ansible.builtin.command: sh /tmp/kubernetes_join_command
  register: joined_or_not
  changed_when: my_output.rc != 0

- name: Join the Worker nodes with the master
  ansible.builtin.debug:
    msg: "{{ joined_or_not.stdout }}"
